export type ManuscriptChapter = {
  id: string;
  title: string;
  subtitle: string;
  paragraphs: string[];
  emphasis?: string;
};

export const manuscriptIntro = {
  label: "MANUSCRITO",
  title: "El Libro del Camino",
  subtitle: "Sobre el viaje del hombre y las fuerzas que lo gobiernan",
  paragraphs: [
    "Desde tiempos antiguos se ha dicho que el hombre no camina solamente sobre la tierra, sino tambien dentro de si mismo.",
    "Y aunque muchos recorren el mundo entero, pocos comprenden que el verdadero viaje ocurre en silencio, dentro del espiritu.",
    "Este manuscrito habla de ese camino.",
    "No del camino de los reyes ni de los conquistadores, sino del camino de todos los hombres.",
    "Un camino que comienza en la inconsciencia, atraviesa una batalla invisible y termina con el nacimiento de una nueva forma de ver.",
    "Quien lea estas paginas comprendera que cada paso dado en el mundo exterior refleja un movimiento mucho mas profundo.",
    "Porque el verdadero viaje del hombre no ocurre en los caminos del mundo, sino en los territorios invisibles de su propia conciencia.",
  ],
};

export const manuscriptChapters: ManuscriptChapter[] = [
  {
    id: "de-los-que-caminan-sin-saber",
    title: "De los que caminan sin saber",
    subtitle: "Sobre la tribu de los Giles",
    paragraphs: [
      "En el principio estan aquellos que caminan.",
      "No saben exactamente hacia donde van, pero avanzan.",
      "Cruzan montanas, llanuras y mares siguiendo horizontes que siempre parecen alejarse.",
      "Son muchos.",
      "Demasiados para contarlos.",
      "Cargan sobre sus espaldas historias, derrotas, suenos y promesas que el tiempo ha dejado en sus vidas.",
      "La tribu avanza.",
      "No hay heroes entre ellos.",
      "No hay figuras extraordinarias.",
      "Solo hombres y mujeres comunes atravesando el paisaje inmenso del mundo.",
      "Algunos miran el mar creyendo que alli se encuentra su destino. Otros creen que el destino esta mas alla de las montanas.",
      "Pero ninguno comprende del todo el camino que recorre.",
      "Mientras avanzan, fuerzas antiguas observan desde dimensiones que los ojos humanos no pueden percibir.",
      "Entidades invisibles, energias silenciosas, presencias que acompanan el movimiento del mundo.",
      "Pero la mayoria no puede verlas.",
      "Muchos caminan toda la vida sin despertar.",
      "Permanecen dentro del transito eterno de la vida, moviendose sin comprender la naturaleza profunda del viaje.",
      "Caminan sin rumbo.",
      "Pero siguen caminando.",
      "Y sin saberlo, entre todos ellos, algunos comienzan a sentir algo distinto.",
      "Una inquietud.",
      "Una senal.",
      "La sospecha de que el camino exterior es solo el reflejo de otro viaje mucho mas profundo.",
    ],
  },
  {
    id: "de-los-cuatro-enemigos",
    title: "De los Cuatro Enemigos",
    subtitle: "Sobre las fuerzas que prueban al hombre",
    paragraphs: [
      "Cuando el hombre comienza a despertar, descubre que el verdadero viaje ocurre dentro de si mismo.",
      "Los antiguos sabios ensenaron que todo aquel que busca comprender debe enfrentar cuatro enemigos.",
      "El primero de ellos es el miedo.",
      "El miedo aparece cuando el hombre percibe lo desconocido. Confunde la mente y empuja al espiritu a retroceder.",
      "Muchos abandonan el camino en este punto.",
      "Pero quien logra atravesar el miedo obtiene claridad.",
      "Y con la claridad llega el segundo enemigo.",
      "La claridad permite comprender el mundo, ordenar las ideas y percibir patrones donde antes solo habia caos.",
      "Pero tambien puede enganar.",
      "El hombre comienza a creer que ya lo entiende todo.",
      "Quien queda atrapado en la claridad deja de buscar.",
      "Quien logra atravesarla descubre el tercer enemigo.",
      "El poder.",
      "El poder seduce.",
      "Promete control, dominio y autoridad sobre los demas.",
      "Muchos se pierden en el, creyendo que dominar el mundo es lo mismo que comprenderlo.",
      "Solo aquellos que logran atravesar el poder sin perder su esencia llegan al ultimo enemigo.",
      "La vejez.",
      "No la vejez del cuerpo, sino la del tiempo que revela el peso de cada decision tomada.",
      "El tiempo desnuda la verdad del camino recorrido.",
      "Quien logra atravesar los cuatro enemigos alcanza algo que pocos hombres conocen.",
      "La capacidad de ver.",
      "No ver con los ojos.",
      "Ver con conciencia.",
    ],
  },
  {
    id: "de-la-muerte-del-antiguo-hombre",
    title: "De la muerte del antiguo hombre",
    subtitle: "Sobre el momento llamado Nunca Mas",
    paragraphs: [
      "Cuando el hombre ha atravesado su batalla interior, llega un instante inevitable.",
      "Las formas antiguas ya no pueden sostenerse.",
      "Las identidades que lo definieron comienzan a quebrarse como madera consumida por el fuego.",
      "Las mascaras se caen.",
      "Las certezas se desintegran.",
      "Entonces ocurre la transformacion.",
      "De la tierra, de la roca y de las raices, el hombre emerge nuevamente, como si el propio mundo estuviera dandole una segunda vida.",
      "El pasado se vuelve ceniza.",
      "Las antiguas versiones del ser se consumen.",
      "El viejo hombre muere.",
      "Este momento ha sido llamado por los sabios de muchas maneras, pero todos coinciden en una verdad:",
      "Despues de este instante no hay regreso posible.",
      "Por eso ha sido nombrado de una sola forma.",
      "Nunca Mas.",
      "Porque quien atraviesa el fuego de su propia transformacion jamas vuelve a ser el mismo.",
      "Nunca mas puede fingir ignorancia.",
      "Nunca mas puede caminar dormido.",
      "El nuevo hombre emerge.",
      "Y con el aparece una nueva forma de conciencia.",
    ],
  },
  {
    id: "de-los-vestigios",
    title: "De los Vestigios",
    subtitle: "Sobre lo que queda despues de la guerra",
    paragraphs: [
      "Despues de toda batalla llega el silencio.",
      "El paisaje conserva senales de lo ocurrido.",
      "Simbolos grabados en la tierra.",
      "Altares fracturados.",
      "Plumas que el viento dispersa lentamente sobre el suelo.",
      "Todo parece guardar una energia que todavia respira bajo la superficie.",
      "Nadie sabe con certeza que ocurrio alli.",
      "Algunos dicen que fue una guerra espiritual.",
      "Otros hablan de un ritual antiguo.",
      "Pero los mas sabios sospechan algo distinto.",
      "Que aquello que sucedio fue el nacimiento de una nueva forma de hombre.",
      "Las fuerzas de la naturaleza libraron su propio combate, el mismo combate que el hombre atraveso dentro de si.",
      "Cuando todo termina, lo unico que queda son vestigios.",
      "Rastros de lo que fue destruido.",
      "Huellas de lo que fue transformado.",
      "Pero entre esos restos tambien aparece algo nuevo.",
      "Una senal.",
      "Un comienzo.",
    ],
  },
  {
    id: "del-ciclo-eterno",
    title: "Del ciclo eterno",
    subtitle: "Sobre el retorno de todas las pruebas",
    paragraphs: [
      "Y mientras algunos despiertan, muchos continuan caminando.",
      "La tribu sigue avanzando hacia el horizonte.",
      "Los Giles siguen su viaje sin comprender completamente el mundo que atraviesan.",
      "Pero ahora, entre ellos, existen quienes han visto.",
      "Y quienes han visto no pueden volver atras.",
      "Porque una vez que el hombre descubre la naturaleza profunda de su propio camino, ya no puede fingir que no lo sabe.",
      "Asi continua el ciclo.",
      "Cada generacion vuelve a comenzar el mismo viaje.",
      "Desde la inconsciencia del caminar…",
      "hasta el momento en que el hombre descubre que la verdadera batalla siempre estuvo dentro de el.",
    ],
  },
];
